# Change these first
owner: ashhhleyyy # Your GitHub organization or username, where this repository lives
repo: status-page # The name of this repository

sites:
  - name: Website (ashhhleyyy.dev)
    url: https://ashhhleyyy.dev/
  - name: Nucleoid website
    url: https://nucleoid.xyz/
  - name: Nucleoid API
    url: https://api.nucleoid.xyz/stats/stats
  - name: Nucleoid Minecraft server
    check: tcp-ping
    url: nucleoid.xyz
    port: 25565

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.ashhhleyyy.dev
  logoUrl: https://ashhhleyyy.dev/assets/pfp.4ae1f7bd.png
  name: Ashhhleyyy - Status
  introTitle: "Ashhhleyyy's status page"
  introMessage: I have several status monitors for different projects I've contributed to, mainly [NucleoidMC](https://nucleoidmc.xyz).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
